# -*- coding: utf-8 -*-
"""Conversion Funnel

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1oEh4NcgFtBqFD6UJmh4xeemGNhJSDZqk
"""

#import data
import pandas as pd
data = pd.read_csv("user_data 2.csv")
print(data.head())

data["user_id"].count()

data["stage"].value_counts()

data["conversion"].value_counts()

# import libraries
import plotly.graph_objects as go
import plotly.io as pio
pio.templates.default = "plotly_white"

#define the funnel stages
funnel_stages = ['homepage', 'product_page', 'cart', 'checkout', 'purchase']

#calculate the number of users and conversions for each stage
num_users = []
num_conversions = []
for stage in funnel_stages:
    stage_users = data[data['stage'] == stage]
    num_users.append(len(stage_users))
    num_conversions.append(stage_users['conversion'].sum())

#create a funnel chart
fig = go.Figure(go.Funnel(
    y=funnel_stages,
    x=num_users,
    textposition='inside',
    textinfo='value',
    name='Users'
))

fig.add_trace(go.Funnel(
    y=funnel_stages,
    x=num_conversions,
    textposition='inside',
    textinfo='value',
    name='Conversions'
))
fig.update_layout(
    title='Funnel Analysis',
    funnelmode='stack'
)

fig.show()